# name: Latest blog post workflow
# on:
#   schedule: # Run workflow automatically
#     - cron: '0 * * * *' # Runs every hour, on the hour
#   workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
# jobs:
#   update-readme-with-blog:
#     name: Update this repo's README with latest blog posts
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: gautamkrishnar/blog-post-workflow@master
#         with:
#           feed_list: "http://createfeed.fivefilters.org/extract.php?url=https%3A%2F%2Fwhitehyun.vercel.app%2F&item=div.my-2+%3E+a&item_title=h2&item_image=img&max=5&order=document&guid=0"
